workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 10
    environment:
      vars:
        JAVA_VERSION: 11
    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
